# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Konstantinos TSANAKAS <konstantinos.tsanakas@soprasteria.com>

# Update the repository sources list
RUN apt-get update

# Install node.js
RUN apt-get -y install nodejs nodejs-legacy npm mysql-server
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install StrongLoop
RUN npm install -g strongloop

# Copy LoopBack Projekt
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /app-server

# Set workdir
WORKDIR /app-server

# Expose the ports
EXPOSE 3000 3001

# Run the arc
#CMD service mysql start && mysql < db.sql && cp -a /tmp/node_modules /app-server && PORT=3001 slc arc